## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
#makeCacheMatrix generate a special "matrix", which is really a list of functions
#including: set(y) - set the matrix
#           get() - get the matrix
#           set_inverse(inv) - set the inverse of the matrix
#           get_inverse() - get the inverse of the matrix
#The special "matrix" can access the matrix and its inverse matrix by using those functions
makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  set <- function(y) {
    x <<- y
    inverse <<- NULL
  }
  get <- function() x
  set_inverse <- function(inv) {
    inverse <<- inv
  }
  get_inverse <- function() inverse
  list(set = set, get = get,
       set_inverse = set_inverse,
       get_inverse = get_inverse)

}


## Write a short comment describing this function
#cacheSolve function return the inverse of the special "matrix" generated by makeCatheMatrix
#if the inverse has been calculated, then return the cached data
#otherwise, use solve function to calculate the inverse 
#and cache it by using the set_inverse() method in the special "matrix"
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inv <- x$get_inverse()
  if(is.null(inv)) {
    mat <- x$get()
    inv <- solve(mat)
    x$set_inverse(inv)
    return(inv)
  } else {
    message('getting cached data')
    return(inv)
  }
}
